Repository Topl/Bifrost, pull requests merged in 2020-05, with the labels that each got.

#370 Jaa mon tools #332
  .gitignore
  build.sbt
  docker/monitoring_tools/docker-compose.yaml
  docker/monitoring_tools/provisioning/grafana/dashboards/bifrostMonitor.json
  docker/monitoring_tools/provisioning/grafana/dashboards/config.yml
  docker/monitoring_tools/provisioning/grafana/datasources/config.yml
  docker/monitoring_tools/provisioning/grafana/env
  docker/monitoring_tools/provisioning/influxdb/env
  project/metals.sbt
  src/main/resources/application.conf
  src/main/resources/logback.xml
  src/main/resources/testnet-private.json
  src/main/scala/bifrost/BifrostApp.scala
  src/main/scala/bifrost/api/http/ProgramApiRoute.scala
  src/main/scala/bifrost/network/NetworkController.scala
  src/main/scala/bifrost/network/peer/PeerManager.scala
  src/main/scala/bifrost/program/ValkyrieFunctions.scala
  src/main/scala/bifrost/scorexMod/GenericApplication.scala
  src/main/scala/bifrost/settings/Settings.scala
  src/main/scala/bifrost/state/BifrostState.scala
Labels: feature

#388 Syncing fix
  src/main/scala/bifrost/forging/Forger.scala
  src/main/scala/bifrost/scorexMod/GenericNodeViewSynchronizer.scala
Labels: bug

#387 remove unneded grafana data volume
  docker/monitoring_tools/docker-compose.yaml
Labels: improvement
